### PR TITLE
1-Creat header for all page and image hero for home page! 2- Create p…

### PR DESCRIPTION
**Pull request by Ashkanamirii**
…rofile page

### CODE REVIEW

**Review by maxerling — CHANGES_REQUESTED** [review]
merge conflict

**Review by baliharko — CHANGES_REQUESTED** [review]
Fix merge conflict!

**Review by kada42 — CHANGES_REQUESTED** [review]
Merge conflict!

**Review by osnorman — CHANGES_REQUESTED** [review]
Change

**Review by kada42 — APPROVED** [review]

**Review by osnorman — APPROVED** [review]
Merge conflicts

**Review by baliharko — APPROVED** [review]

**Review by maxerling — APPROVED** [review]

**Pull request merged**
